spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/commerce
    username: calaf
    password: 221031
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false